### ISSUE TITLE
Code formatter

### ISSUE THREAD

**Issue by guilhermedeoliveira** [Paulof53/react-app#7]
## Context
Três ferramentas usadas no desenvolvimento de web moderno ajudam na padronização e na qualidade de um código, além de melhorar a DX (Developer Experience):

```
- linter (eslint)
- code formatter (prettier)
- tipagem (TypeScript, flow)
```
O foco dessa issue é o code formatter.

Ferramentas de code formatting ajudam a automatizar e unificar a formatação do código para que todos os desenvolvedores de um projeto mantenham uma padronização.

## Proposed solution
[prettier](https://prettier.io/docs/en/install.html) é a ferramenta de facto utilizada no ecossistema do javascript. É praticamente um padrão utilizado nos projetos web modernos.

## Installation
Não precisa instalar globalmente no teu PC a ferramenta. Aconselho deixar como uma `devDependency` dentro do teu projeto.

```
npm install --save-dev prettier
```

## ToDo
[] Instalar a extensão do prettier no vscode
[] Criar um arquivo chamado `.prettierrc` na raiz do teu projeto

Sugestão sugerida de configuração
```
{
  "useTabs": false,
  "printWidth": 80,
  "tabWidth": 2,
  "singleQuote": true,
  "trailingComma": "es5",
  "jsxBracketSameLine": false,
  "semi": false,
  "arrowParens": "avoid"
}
```
Estudar o que significa cada uma dessas regras propostas
[] Criar um arquivo chamado `.prettierignore`
Sugestão sugerida de configuração
```
node_modules
```
[] Verificar no canto direito inferior do vscode (barra azul) se a opção de formatação está habilitada. Porque o vscode já tem integração built in com o prettier

**Comment by Paulof53** [comment]
Instalação realizada;
Arquivos .prettierrc e .prettierignore criados.

Usei a documentação do Prettier para saber os conceitos de cada configuração sugerida. Achei melhor manter em inglês para não prejudicar o entendimento. 

"useTabs": false,  = Prettier uses spaces to align things.
  "printWidth": 80, = Specify the number of spaces per indentation-level.
  "tabWidth": 2,  = Indent lines with tabs instead of spaces.
  "singleQuote": true, =  Use single quote.
  "trailingComma": "es5", = Trailing commas where valid in ES5 (objects, arrays, etc.)
  "jsxBracketSameLine": false,  = Put the > of a multi-line JSX element at the end of the last line instead of being alone on the next line (does not apply to self closing elements).
  "semi": false, = Only add semicolons at the beginning of lines that may introduce ASI failures.
  "arrowParens": "avoid"  = Omit parens when possible.

**Comment by guilhermedeoliveira** [comment]
É isso aí mesmo. O legal que além de fazer o setup do prettier no projeto, ainda vê alguns padrões que podem ser usados no javascript por meio dessas regras.
